name = "vss_rust"
description = "FFI bindings for UTF-8 string exchange between Rust and Ada VSS"
version = "0.1.3-dev"

authors = ["Your Name"]
maintainers = ["Your Name <example@example.com>"]
maintainers-logins = ["SergeyNM"]
licenses = "Apache-2.0"
website = "https://github.com/SergeyNM/vss-rust"
tags = ["ffi", "strings", "vss", "rust", "interop"]

project-files = ["gnat/vss_rust.gpr"]

[[depends-on]]
vss_text = "^26.0.0"
vss_extra = "^26.0.0"
